### ISSUE TITLE
Consider targeting netstandard1.x instead of netcoreapp1.x

### ISSUE THREAD

**Issue by tintoy** [omarbesiso/Ximo#1]
I could be wrong here, but from what I remember, only programs (i.e. assemblies  with a `Main()` method) target `netcoreapp1.x`. Libraries normally target `netstandard1.x`. If someone builds an assembly targeting `netcoreapp1.3` (for example), they won't be able to reference your libraries because they're targeting `netcoreapp1.0`.

**Comment by omarbesiso** [comment]
Unfortunately VS 2017 RC tooling has very aggressive warnings that cannot be shut down when using .NET standard. I will leave it for now and migrate when VS 2017 RTM is released.

**Comment by omarbesiso** [comment]
Ok I have converted all projects except the console app to .NET Standard 1.6.1. To supress the warnings in Visual Studio 2017 RC about the downgrade of nuget packages I did the following.

`<PropertyGroup>
    <TargetFramework>netstandard1.6</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <NetStandardImplicitPackageVersion>1.6.1</NetStandardImplicitPackageVersion>
  </PropertyGroup>`

This is explained here:

[http://stackoverflow.com/questions/42320021/vs-2017-rc-i-can-not-update-netstandard-library-in-nuget](url)

**Comment by tintoy** [comment]
https://github.com/DimensionDataResearch/cloudcontrol-powershell-core/blob/master/src/DD.CloudControl.Powershell/DD.CloudControl.Powershell.csproj#L9

;-)

**Comment by tintoy** [comment]
(sorry if you'd mentioned the error I could have saved you some time - ran into this a while back and had to work it out the hard by by digging into the `.targets` files.

You can also do (something like) this, I believe, which has the basically the same effect:

```xml
<PackageReference Update="NETStandard.Library" Version="1.6.1" />
```

**Comment by omarbesiso** [comment]
Yeah. the other problem with the tooling is the error keeps coming up even if you cleanup solution. Had to manually cleanup bin and obj directories and rebuilt after making the change. Only then it compiles.

Yeah PackageReference is mentioned in the link as well. 

All good now.

**Comment by omarbesiso** [comment]
Closing issue. Thanks Adam.

**Comment by tintoy** [comment]
No worries! :)

PS. `obj\project.assets.json` is the equivalent of `project.lock.json` - RC4 tooling definitely doesn't always get things right here and sometimes you do have to delete these files and `dotnet restore` to get things working. Also make sure `dotnet migrate` actually uses `ProjectReference` elements where appropriate (not `PackageReference`)...
